version: '3'

services:
  front:
    image: node:15.14.0-alpine3.12
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0
    volumes:
      - ./front_src/.:/usr/src/app
    working_dir: /usr/src/app
    env_file:
      - front.env

  back:
    image: node:15.14.0-alpine3.12
    command: sh -c "npm install && npm run start:dev"
    ports:
      - "8080:8080"
    volumes:
      - ./back_src/.:/usr/src/app
    working_dir: /usr/src/app
    env_file:
      - db.env
      - back.env

  postgres:
    image: postgres:latest
    volumes:
      - ./db_entrypoint:/docker-entrypoint-initdb.d
      - ./db_data:/var/lib/postgresql/data
    env_file:
      - db.env

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8081:80"
    volumes:
      - ./pgadmin:/root/.pgadmin
    env_file:
      - db_admin.env